# Overview
This notebook is for Data Analysis Learning. 

## Jupyter Notebook

### Run Jupyter Notebook
Export path since it is installed under Python 3:
```
jupyter notebook
export PATH="/Users/karinwan/Library/Python/3.8/bin:$PATH"
```
Notebook should be opened in browser (http://localhost:8888/tree).

### Dependency Installation
```
pip3 install scipy
```

### Keyboard shotcuts
| shortcut | usage |
| -------- | ----- |
| A | create a cell Above the current selected cell |
| B | ~ Below ~ |
| D+D | delete cell |
| M | switch cell to Markdown |
| Y | switch cell to Python code |
| crtl+return | run current cell |
| shift+return | run current and move to the next |
| Z | undo |
|  |  |

## NumPy

the fundamental package for scientific computing with Python

In [201]:
import numpy as np
import sys

### create number with fized zise


GB -> MB -> KB -> B(bytes) -> b(bits)

List in Python may not put list items in continugous positions. High relience on CPU. NumPy is faster. 

In [202]:
# one byte integer
np.int8
# two byte integer
np.int16
# four byte integer
np.int32

numpy.int32

### Performance

In [203]:
sys.getsizeof([1])

64

In [204]:
np.array([1]).nbytes

8

In [205]:
l = list(range(100000))
a = np.arange(100000)

In [206]:
%time np.sum(a ** 2)

CPU times: user 364 µs, sys: 458 µs, total: 822 µs
Wall time: 454 µs


333328333350000

In [207]:
%time sum([x ** 2 for x in l])

CPU times: user 18 ms, sys: 912 µs, total: 18.9 ms
Wall time: 18.9 ms


333328333350000

### Basic Numpy Arrays

#### Create

In [208]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [209]:
a = np.array([1, 2, 3, 4])

In [210]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [211]:
a[0], a[3]

(1, 4)

In [212]:
a[[0, 2, -1]]   # select and create new array

array([1, 3, 4])

#### Slicing

In [213]:
a[1:]   #all lines starting from line 1

array([2, 3, 4])

In [214]:
a[:3]   # all lines up to line 3 excluded

array([1, 2, 3])

In [215]:
a[1:-1]

array([2, 3])

In [216]:
a[::2]  # every other line / sampling (1 item every 2)

array([1, 3])

In [217]:
a[::]  # sampling of 1

array([1, 2, 3, 4])

In [218]:
a[::-1] # reverse order

array([4, 3, 2, 1])

#### Array Types

In [219]:
a

array([1, 2, 3, 4])

In [220]:
a.dtype

dtype('int64')

In [221]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [222]:
b.dtype

dtype('float64')

In [223]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [224]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [225]:
c = np.array(['a', 'b', 'c'])

In [226]:
c.dtype

dtype('<U1')

In [227]:
d = np.array([{'a': 1}, sys])

In [228]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [229]:
d.dtype

dtype('O')

#### Dimension and shapes

##### 2D

In [230]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [231]:
A.shape

(3, 3)

In [232]:
A.size

9

In [233]:
A.ndim

2

##### 3D

In [234]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [235]:
B.shape

(2, 2, 3)

In [236]:
B.size

12

In [237]:
B.ndim

3

##### Indexing and Slicing of Matrices

In [238]:
A = np.array([
#    0  1  2
    [1, 2, 3],  # 0
    [4, 5, 6],  # 1
    [7, 8, 9]   # 2
])

In [239]:
A[1]

array([4, 5, 6])

In [240]:
A[1][0] 

4

In [241]:
# A[d1, d2, d3, ...]
A[1, 0]

4

In [242]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [244]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [245]:
A[1] = np.array([10, 10, 10])

In [246]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [247]:
A[2] = 99

In [248]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#### Summary Statistics

In [249]:
a = np.array([1, 2, 3, 4])

In [250]:
a.sum()

10

In [251]:
a.mean()

2.5

In [252]:
a.std()

1.118033988749895

In [253]:
a.var()

1.25

In [254]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [255]:
A.sum()

45

In [256]:
A.mean()

5.0

In [257]:
A.std()

2.581988897471611

In [258]:
# sum of each column
A.sum(axis=0)

array([12, 15, 18])

In [259]:
# sum of each row
A.sum(axis=1)

array([ 6, 15, 24])

In [260]:
A.mean(axis=0)

array([4., 5., 6.])

In [261]:
A.mean(axis=1)

array([2., 5., 8.])

In [262]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [263]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#### Broadcasting and Vectorized operations

In [264]:
a = np.arange(4)

In [265]:
a

array([0, 1, 2, 3])

In [266]:
a + 10

array([10, 11, 12, 13])

In [267]:
a * 10

array([ 0, 10, 20, 30])

In [268]:
a

array([0, 1, 2, 3])

In [269]:
a += 100

In [270]:
a

array([100, 101, 102, 103])

In [271]:
l = [0, 1, 2, 3]

In [272]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [273]:
a = np.arange(4)

In [274]:
a

array([0, 1, 2, 3])

In [275]:
b = np.array([10, 20, 30, 40])

In [276]:
a + b

array([10, 21, 32, 43])

In [277]:
a * b

array([  0,  20,  60, 120])

#### Boolean arrays / filtering

In [278]:
a = np.arange(4)

In [279]:
a

array([0, 1, 2, 3])

In [280]:
a[[0, -1]]

array([0, 3])

In [281]:
a[[True, False, False, True]]

array([0, 3])

In [282]:
a >= 2

array([False, False,  True,  True])

In [283]:
a[a >= 2]

array([2, 3])

In [284]:
a.mean()

1.5

In [285]:
a[a > a.mean()]

array([2, 3])

In [286]:
# Not
a[~(a > a.mean())]

array([0, 1])

In [287]:
# And
a[(a == 0) | (a == 1)]

array([0, 1])

In [288]:
# Or
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [289]:
A = np.random.randint(100, size=(3, 3))

In [290]:
A

array([[34, 99, 74],
       [ 1, 28, 84],
       [83, 12, 87]])

In [291]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([34, 74, 28, 83, 87])

In [292]:
A > 30

array([[ True,  True,  True],
       [False, False,  True],
       [ True, False,  True]])

In [293]:
A[A > 30]

array([34, 99, 74, 84, 83, 87])

#### Linear Algebra

In [294]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [295]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [296]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [297]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [298]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [299]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [300]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Pandas

In [301]:
import pandas as pd
import numpy as np

### Pandas Series

#### Create

We'll analyze "The Group of Seven" (Canada, France, Germany, Italy, Japan, UK, US). We'll start by analyzing population, and for that, we'll use `pandas.Series` object. 

In [302]:
# 
g7_pop = pd.Series([35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523])

In [303]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [304]:
g7_pop.name = 'G7 Population in millions'

In [305]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Population in millions, dtype: float64

In [306]:
g7_pop.dtype

dtype('float64')

In [307]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [308]:
type(g7_pop.values)

numpy.ndarray

A Series has an **index**, that's similar to the automatic index assigned to Python's lists:

In [309]:
g7_pop[2]

80.94

In [310]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In contrast to lists, we can explicitly define the index:

In [311]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [312]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

ordered sequence of items, more like dictionary

In [313]:
pd.Series(g7_pop, index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: G7 Population in millions, dtype: float64

#### Indexing

In [314]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [315]:
g7_pop['Canada']

35.467

Use numeric positions

In [316]:
g7_pop.iloc[0]

35.467

In [317]:
g7_pop.iloc[-1]

318.523

In [318]:
g7_pop[['Italy', 'France']]

Italy     60.665
France    63.951
Name: G7 Population in millions, dtype: float64

In [319]:
g7_pop.iloc[[0, 1]]

Canada    35.467
France    63.951
Name: G7 Population in millions, dtype: float64

In [320]:
g7_pop['Canada': 'Italy']

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: G7 Population in millions, dtype: float64

#### Conditional selection (boolean arrays)

In [321]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [322]:
g7_pop > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 Population in millions, dtype: bool

In [323]:
g7_pop[g7_pop > 70]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [324]:
g7_pop.mean()

107.30257142857144

In [325]:
g7_pop.std()

97.24996987121581

`~` not

`|` or

`&` and

#### Operations and methods

In [326]:
g7_pop * 1_000_000

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 Population in millions, dtype: float64

In [327]:
g7_pop[(g7_pop > 80) & (g7_pop < 150)]

Germany     80.940
Japan      127.061
Name: G7 Population in millions, dtype: float64

#### Modifying series

In [328]:
g7_pop['Canada'] = 40.5

In [329]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [330]:
g7_pop.iloc[-1] = 500

In [331]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
Name: G7 Population in millions, dtype: float64

In [332]:
g7_pop[g7_pop < 70]

Canada            40.500
France            63.951
Italy             60.665
United Kingdom    64.511
Name: G7 Population in millions, dtype: float64

In [333]:
g7_pop[g7_pop < 70] = 99.99

In [334]:
g7_pop

Canada             99.990
France             99.990
Germany            80.940
Italy              99.990
Japan             127.061
United Kingdom     99.990
United States     500.000
Name: G7 Population in millions, dtype: float64

### DataFrames

One column of a DataFrame is a Series

#### Create

Dataframe looks a lot like a table. Most of the time is created by pulling data from a Database, a csv file or  the website. 

In [335]:
df = pd.DataFrame({
    'Population' : [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    'GDP' : [1785387, 2833687, 3874437, 2167744, 4602367, 2950039, 17348075],
    'Surface Area' : [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
    'HDI' : [0.913, 0.888, 0.916, 0.873, 0.891, 0.907, 0.915],
    'Continent' : ['America', 'Europe', 'Europe', 'Europe', 'Asia', 'Europe', 'America']
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

# The columns argument is optional. If not specified, the columns will be ordered alphabetically.

In [336]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [337]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [338]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [339]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [340]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [341]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes


In [342]:
df.shape

(7, 5)

In [343]:
df.size

35

In [344]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [345]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [346]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
Name: count, dtype: int64

#### Indexing, Selection and Slicing

In [347]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [348]:
# Select individual row, return as Series
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [349]:
# Select row by index, return as Series
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [350]:
# Select individual column, return as Series
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [351]:
df['Population'].to_frame()

Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

In [352]:
# DataFrame
df[['Population', 'GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [353]:
df.loc['France':'Italy]']

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [199]:
df.iloc[[0, 1, -1]]

Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [354]:
df.iloc[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [200]:
df.iloc[1:3, 3]

France     0.888
Germany    0.916
Name: HDI, dtype: float64

In [355]:
df.iloc[1:3, [0, 3]]

Population    HDI
France       63.951  0.888
Germany      80.940  0.916

#### Conditional selection (boolean arrays)

In [356]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [357]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [358]:
df.loc[df['Population'] > 70]

Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [359]:
df.loc[df['Population'] > 70, ['Population', 'GDP']]

Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

#### Dropping stuff

In [360]:
df.drop('Canada')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [361]:
df.drop(['Canada', 'Japan'])

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [362]:
df.drop(columns=['Population', 'HDI'])

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [363]:
df.drop(['Italy', 'Canada'], axis=0)

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [364]:
df.drop(['Population', 'HDI'], axis=1)

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

#### Operations

In [369]:
df[['GDP', 'HDI']]

GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [370]:
df[['GDP', 'HDI']]/ 100

GDP      HDI
Canada           17853.87  0.00913
France           28336.87  0.00888
Germany          38744.37  0.00916
Italy            21677.44  0.00873
Japan            46023.67  0.00891
United Kingdom   29500.39  0.00907
United States   173480.75  0.00915

Operations with Series work at a column level, broadcasting down the rows. 

In [371]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])
df[['GDP', 'HDI']] + crisis

GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

#### Modifying

##### Adding a new column to the DataFrame

In [389]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

In [374]:
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [390]:
df['Language'] = langs

In [376]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

##### Replacing values per column

In [391]:
df['Language'] = 'English'

In [378]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

##### Renaming Columns

In [392]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index={
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    }
)

Population       GDP  Surface Area  Human Development Index  \
Canada       35.467   1785387       9984670                    0.913   
France       63.951   2833687        640679                    0.888   
Germany      80.940   3874437        357114                    0.916   
Italy        60.665   2167744        301336                    0.873   
Japan       127.061   4602367        377930                    0.891   
UK           64.511   2950039        242495                    0.907   
USA         318.523  17348075       9525067                    0.915   

        Continent Language  
Canada    America  English  
France     Europe  English  
Germany    Europe  English  
Italy      Europe  English  
Japan        Asia  English  
UK         Europe  English  
USA       America  English

In [380]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [388]:
df.rename(index=lambda x: x.lower())

Population       GDP  Surface Area    HDI Continent
canada              35.467   1785387       9984670  0.913   America
france              63.951   2833687        640679  0.888    Europe
germany             80.940   3874437        357114  0.916    Europe
italy               60.665   2167744        301336  0.873    Europe
japan              127.061   4602367        377930  0.891      Asia
united kingdom      64.511   2950039        242495  0.907    Europe
united states      318.523  17348075       9525067  0.915   America

##### Dropping columns

In [393]:
df.drop('Language', axis=1, inplace=True)

In [394]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

##### Adding values

In [401]:
# append was removed in pandas 0.25.0
# df.append(pd.Series({

# This is the new way to append, but has problems that name is not successfully added
# df.loc[len(df)] = pd.Series({
#     'Population': 3,
#     'GDP': 5
# }, name='China')

##### More redical index changes

In [410]:
df

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
7                    3.000         5.0           NaN    NaN       NaN
8                    3.000         5.0           NaN    NaN       NaN

In [411]:
df.reset_index()

index  Population         GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387.0     9984670.0  0.913   America
1          France      63.951   2833687.0      640679.0  0.888    Europe
2         Germany      80.940   3874437.0      357114.0  0.916    Europe
3           Italy      60.665   2167744.0      301336.0  0.873    Europe
4           Japan     127.061   4602367.0      377930.0  0.891      Asia
5  United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
6   United States     318.523  17348075.0     9525067.0  0.915   America
7               7       3.000         5.0           NaN    NaN       NaN
8               8       3.000         5.0           NaN    NaN       NaN

In [412]:
df.set_index('Population')

GDP  Surface Area    HDI Continent
Population                                           
35.467       1785387.0     9984670.0  0.913   America
63.951       2833687.0      640679.0  0.888    Europe
80.940       3874437.0      357114.0  0.916    Europe
60.665       2167744.0      301336.0  0.873    Europe
127.061      4602367.0      377930.0  0.891      Asia
64.511       2950039.0      242495.0  0.907    Europe
318.523     17348075.0     9525067.0  0.915   America
3.000              5.0           NaN    NaN       NaN
3.000              5.0           NaN    NaN       NaN

#### Creating columns from other columns

In [413]:
df[['Population', 'GDP']]

Population         GDP
Canada              35.467   1785387.0
France              63.951   2833687.0
Germany             80.940   3874437.0
Italy               60.665   2167744.0
Japan              127.061   4602367.0
United Kingdom      64.511   2950039.0
United States      318.523  17348075.0
7                    3.000         5.0
8                    3.000         5.0

In [414]:
df['GDP'] / df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
7                     1.666667
8                     1.666667
dtype: float64

In [415]:
df['GDP per Capita'] = df['GDP'] / df['Population']

In [416]:
df

Population         GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387.0     9984670.0  0.913   America   
France              63.951   2833687.0      640679.0  0.888    Europe   
Germany             80.940   3874437.0      357114.0  0.916    Europe   
Italy               60.665   2167744.0      301336.0  0.873    Europe   
Japan              127.061   4602367.0      377930.0  0.891      Asia   
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe   
United States      318.523  17348075.0     9525067.0  0.915   America   
7                    3.000         5.0           NaN    NaN       NaN   
8                    3.000         5.0           NaN    NaN       NaN   

                GDP per Capita  
Canada            50339.385908  
France            44310.284437  
Germany           47868.013343  
Italy             35733.025633  
Japan             36221.712406  
United Kingdom    45729.239975  
United States     54464.120330  
7                     1.666667  
8                     1.666667

#### Statistical info

In [417]:
df.head()

Population        GDP  Surface Area    HDI Continent  GDP per Capita
Canada       35.467  1785387.0     9984670.0  0.913   America    50339.385908
France       63.951  2833687.0      640679.0  0.888    Europe    44310.284437
Germany      80.940  3874437.0      357114.0  0.916    Europe    47868.013343
Italy        60.665  2167744.0      301336.0  0.873    Europe    35733.025633
Japan       127.061  4602367.0      377930.0  0.891      Asia    36221.712406

In [418]:
df.describe()

Population           GDP  Surface Area       HDI  GDP per Capita
count    9.000000  9.000000e+00  7.000000e+00  7.000000        9.000000
mean    84.124222  3.951305e+06  3.061327e+06  0.900429    34963.235041
std     95.961105  5.258953e+06  4.576187e+06  0.016592    20716.288608
min      3.000000  5.000000e+00  2.424950e+05  0.873000        1.666667
25%     35.467000  1.785387e+06  3.292250e+05  0.889500    35733.025633
50%     63.951000  2.833687e+06  3.779300e+05  0.907000    44310.284437
75%     80.940000  3.874437e+06  5.082873e+06  0.914000    47868.013343
max    318.523000  1.734808e+07  9.984670e+06  0.916000    54464.120330

In [419]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, Canada to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Population      9 non-null      float64
 1   GDP             9 non-null      float64
 2   Surface Area    7 non-null      float64
 3   HDI             7 non-null      float64
 4   Continent       7 non-null      object 
 5   GDP per Capita  9 non-null      float64
dtypes: float64(5), object(1)
memory usage: 804.0+ bytes


### Reading external data
https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-pandas/blob/master/5%20-%20Pandas%20-%20Reading%20CSV%20and%20Basic%20Plotting.ipynb

- pandas.read_csv
- read SQL
- read Excel
- read XML
- read JSON
- read HTML

In [420]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Data Cleaning